site_name: LearnCentre
site_description: "Tutorial documentation of selected open scource programs"
site_author: "Eli Volschenk and contributors"
docs_dir: ./docs/src
site_dir: ./docs/site
repo_name: "LearnCentre"
repo_url: "https://github.com/EliVolsch/LearnCentre"
edit_uri: "https://github.com/EliVolsch/LearnCentre/blob/main/docs/"

copyright: LearnCentre and Contributors

# Configuration
theme:
  name: material
  language: en
  direction: ltr
  include_search_page: true
  search_index_only: true
  extra_css:
    - stylesheets/extra.css
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    # - navigation.expand
    # - navigation.prune # cannot work with naviation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-6
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  icon:
    logo: material/book

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/unicef-drp/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/UNICEF
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/unicef/
    - icon: fontawesome/solid/earth-africa
      link: https://www.unicef.org/

markdown_extensions:
  - attr_list # lets us resize images see https://github.com/mkdocs/mkdocs/issues/1678#issuecomment-455500757
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  #- mdx_truly_sane_lists
  - toc:
      permalink:
        true
        #slugify: !!python/name:pymdownx.slugs.slugify
  - pymdownx.snippets:
      base_path: .
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
plugins:
  - mkdocs-video
  - search

nav:
  - Home:
      - /index.md # short intro on project here
  - Learning Materials:
      - /explore.md # this will be menu file with all courses
      - "":
        - "": 
          - /figma/index.md # (use "": to load pages without displaying them)
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
          - "": /figma/fundametals/
      - "": /mkdocs/index.md
  - Contribute:
      - index.md #Why should people contribute to this platform? Link contributors gh handles
      - How to contribute: contribute.md
      - Contribution Guidelines: guidelines.md
  - About:
      - /index.md
      - Terms of use: about/terms.md
      - License: about/license.md
  - Help: help.md
